name: Build iOS IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploying
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2



    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ProfilehellowordAdHot.mobileprovision

	 - name: Decode and install certificate
        run: |
 # 解码并安装证书
          echo "${{ secrets.CERTIFICATE }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

    - name: Install CocoaPods
      run: |
        pod install

    - name: Build the app
      run: |
        xcodebuild -workspace helloword.xcworkspace \
                   -scheme helloword \
                   -sdk iphoneos \
                   -configuration AdHoc \
                   -archivePath $PWD/build/helloword.xcarchive \
                   clean archive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath $PWD/build/helloword.xcarchive \
                   -exportOptionsPlist exportOptions.plist  # 需要根据你的项目设置创建此文件
                   -exportPath $PWD/build \
           	   -allowProvisioningUpdates \
            	   -exportArchive | xcpretty
