name: Build iOS IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploying
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ProfilehellowordAdHot.mobileprovision

    - name: Decode and install certificate
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" 


    