name: Build iOS IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploying
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode and install certificate
      run: |
        echo "${{ secrets.CERTIFICATE_PASSWORD }}" | base64 --decode > certificate.p12
        security import certificate.p12 -P "${{ secrets.CERTIFICATE }}" -A
        security list-keychains -s ~/Library/Keychains/build.keychain
	security default-keychain -s ~/Library/Keychains/build.keychain
	security unlock-keychain -p "" ~/Library/Keychains/build.keychain
        security set-key-partition-list -S apple-tool:,apple: -s ~/Library/Keychains/build.keychain

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ProfilehellowordAdHot.mobileprovision

    - name: Install CocoaPods
      run: |
        pod install

    - name: Build the app
      run: |
        xcodebuild -workspace helloword.xcworkspace \
                   -scheme helloword \
                   -sdk iphoneos \
                   -configuration AdHoc \
                   -archivePath $PWD/build/helloword.xcarchive \
                   clean archive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath $PWD/build/helloword.xcarchive \
                   -exportOptionsPlist exportOptions.plist  # 需要根据你的项目设置创建此文件
                   -exportPath $PWD/build \
           	   -allowProvisioningUpdates \
            	   -exportArchive | xcpretty
